import api from "@/lib/api/api";
import type {
  GetPostsParams,
  PaginatedPosts,
  Post,
  SharePostResponse,
} from "@/features/posts/types/post.types";

interface BackendResponse<T> {
  success: boolean;
  message: string;
  data: T;
  statusCode: number;
}

export const PostsAPI = {
  /**
   * Fetch published posts using cursor pagination.
   */
  getPosts: async (params: GetPostsParams = {}): Promise<PaginatedPosts> => {
    const response = await api.get<BackendResponse<PaginatedPosts>>("/posts", {
      params: {
        ...(params.cursor ? { cursor: params.cursor } : {}),
        limit: params.limit ?? 20,
        ...(params.authorId ? { authorId: params.authorId } : {}),
      },
    });

    return response.data.data;
  },

  /**
   * Fetch a single post by its ID.
   */
  getPostById: async (postId: string): Promise<Post> => {
    const response = await api.get<BackendResponse<Post>>(`/posts/${postId}`);

    return response.data.data;
  },

  /**
   * Create a post.
   * The backend expects multipart/form-data.
   */
  createPost: async (formData: FormData): Promise<Post> => {
    const response = await api.post<BackendResponse<Post>>(
      "/posts/create",
      formData,
    );

    return response.data.data;
  },

  /**
   * Update a post.
   * The backend expects multipart/form-data.
   */
  updatePost: async (postId: string, formData: FormData): Promise<Post> => {
    const response = await api.put<BackendResponse<Post>>(
      `/posts/${postId}`,
      formData,
    );

    return response.data.data;
  },

  /**
   * Use the backend's existing like endpoint.
   */
  likePost: async (
    postId: string,
  ): Promise<{ status: "liked" | "unliked" }> => {
    const response = await api.post<
      BackendResponse<{ status: "liked" | "unliked" }>
    >(`/posts/${postId}/like`);

    return response.data.data;
  },

  /**
   * Soft-delete a post using the existing backend route.
   */
  deletePost: async (postId: string): Promise<void> => {
    await api.delete<BackendResponse<null>>(`/posts/${postId}`);
  },

  /**
   * Record a share and retrieve the URL generated by the backend.
   */
  sharePost: async (
    postId: string,
    platform?: string,
  ): Promise<SharePostResponse> => {
    const response = await api.post<BackendResponse<SharePostResponse>>(
      `/posts/${postId}/share`,
      platform ? { platform } : {},
    );

    return response.data.data;
  },
};
